use std::path::PathBuf;
use std::{env, fs};

use crate::build_scripts::parser::types::Function;

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();

    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
            result.push_str(&ch.to_lowercase().to_string());
        } else {
            result.push(ch.to_lowercase().next().unwrap_or(ch));
        }
    }

    result
}

pub(crate) fn generate_functions_with_modules(file_modules: &[(String, Vec<Function>)]) {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"));
    let dest = manifest_dir.join("src").join("functions.rs");

    let mut code = String::new();
    code.push_str("// This file is auto-generated by build.rs\n");
    code.push_str("// Do not edit manually - changes will be overwritten during build\n\n");

    for (module_name, functions) in file_modules {
        let rust_module_name = to_snake_case(module_name);

        code.push_str(&format!("pub mod {} {{\n", rust_module_name));
        code.push_str("    use crate::ffi::call::call_haskell_typed;\n");
        code.push_str("    use crate::ffi::value::Value;\n\n");

        for function in functions {
            code.push_str("    ");
            code.push_str(&generate_function(function, module_name).replace('\n', "\n    "));
            code.push('\n');
            code.push('\n');
        }

        code.push_str("}\n\n");
    }

    fs::write(&dest, code).expect("Failed to write generated Rust bindings");
}

fn generate_function(function: &Function, module_name: &str) -> String {
    let args_sig = function
        .args
        .iter()
        .map(|arg| format!("{}: {}", arg.name, arg.r#type.rust_type()))
        .collect::<Vec<_>>()
        .join(", ");

    let args_values = function
        .args
        .iter()
        .map(|arg| arg.r#type.rust_value_ctor(&arg.name))
        .collect::<Vec<_>>()
        .join(", ");

    let return_type = function.r#return.rust_type();
    let converter = function.r#return.return_converter();
    let qualified_name = format!("{}_{}", to_snake_case(module_name), function.name);

    format!(
        "pub fn {name}({args_sig}) -> {return_type} {{
    let result = call_haskell_typed(\"{qualified_name}\", &[{args_values}]);
    result.{converter}()
}}",
        name = function.name,
        args_sig = args_sig,
        return_type = return_type,
        qualified_name = qualified_name,
        args_values = args_values,
        converter = converter,
    )
}
