// This file is auto-generated by build.rs
// Do not edit manually - changes will be overwritten during build

pub mod math {
    use vinculum_hs::ffi::call::call_haskell_typed;
    #[allow(unused_imports)]
    use vinculum_hs::ffi::value::{AcceptedTypes, Value};

    /// hey
    /// desc
    /// a
    /// d
    #[allow(non_snake_case, dead_code)]
    pub fn add(a: i64, b: i64) -> i64 {
        call_haskell_typed("math_add", &[Value::<()>::Int64(a), Value::<()>::Int64(b)])
            .try_into().expect("internal FFI type error: invalid return type")
    }

    /// Fonction 2
    /// a
    #[allow(non_snake_case, dead_code)]
    pub fn multiply(a: i64, b: i64) -> i64 {
        call_haskell_typed("math_multiply", &[Value::<()>::Int64(a), Value::<()>::Int64(b)])
            .try_into().expect("internal FFI type error: invalid return type")
    }

    #[allow(non_snake_case, dead_code)]
    pub fn factorial(n: i64) -> i64 {
        call_haskell_typed("math_factorial", &[Value::<()>::Int64(n)])
            .try_into().expect("internal FFI type error: invalid return type")
    }

}

