// This file is auto-generated by build.rs
// Do not edit manually - changes will be overwritten during build

use crate::value::{Value, call_haskell_typed};

pub fn add(arg1: i64, arg2: i64) -> i64 {
    let result = call_haskell_typed("add", &[Value::Int64(arg1), Value::Int64(arg2)]);
    Value::into_int64(result)
}
